<?php

namespace AppBundle\Repository;

/**
 * RetailProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailProductRepository extends \Doctrine\ORM\EntityRepository
{
}
